import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Leaf, LocaleTree } from '../locale-files.js';
import { collectArgOrder, findIcuMessage, hasSecondIcuMessage, toPositional } from './transform.js';

// Android emitter: values-<lang>/strings.xml (source language → values/).
// Keys `ns:a.b` become resource names `ns_a_b`; ICU plural → <plurals>;
// string arrays → <string-array>; named placeholders → positional %n$s
// with the argument order taken from the SOURCE language string.

const ANDROID_PLURAL_QUANTITIES = new Set(['zero', 'one', 'two', 'few', 'many', 'other']);
const EXPLICIT_QUANTITY: Record<string, string> = { '=0': 'zero', '=1': 'one', '=2': 'two' };

export function androidResourceName(namespace: string, key: string): string {
  const raw = namespace ? `${namespace}_${key}` : key;
  return raw.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').replace(/^(\d)/, 'k$1');
}

export function escapeAndroid(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n');
}

function positionalize(value: string, sourceValue: string, hash: boolean): string {
  const order = collectArgOrder(sourceValue, hash);
  return toPositional(value, order, (i, token) => (token === '#' ? `%${i}$d` : `%${i}$s`));
}

export interface AndroidWarnings {
  warnings: string[];
}

interface Entry {
  kind: 'string' | 'plurals' | 'array';
  name: string;
  value?: string;
  items?: { quantity: string; value: string }[];
  arrayItems?: string[];
}

function walk(
  tree: LocaleTree,
  sourceTree: LocaleTree,
  namespace: string,
  prefix: string,
  out: Entry[],
  warn: AndroidWarnings,
): void {
  if (Array.isArray(tree)) {
    return; // handled by parent as string-array
  }
  for (const [k, v] of Object.entries(tree)) {
    const path = prefix ? `${prefix}.${k}` : k;
    const sourceValue = Array.isArray(sourceTree) ? undefined : (sourceTree as Record<string, LocaleTree | Leaf>)[k];
    if (Array.isArray(v)) {
      const items = v.filter((x): x is string => typeof x === 'string');
      out.push({ kind: 'array', name: androidResourceName(namespace, path), arrayItems: items });
      continue;
    }
    if (v !== null && typeof v === 'object') {
      walk(v, (sourceValue ?? {}) as LocaleTree, namespace, path, out, warn);
      continue;
    }
    if (typeof v !== 'string' || v === '') {
      continue; // numbers/booleans/null/empty are not string resources
    }
    const src = typeof sourceValue === 'string' ? sourceValue : v;
    const name = androidResourceName(namespace, path);

    if (hasSecondIcuMessage(src)) {
      warn.warnings.push(`${namespace}:${path} — multiple ICU blocks; exported verbatim`);
      out.push({ kind: 'string', name, value: escapeAndroid(v) });
      continue;
    }

    const icu = findIcuMessage(v);
    const srcIcu = findIcuMessage(src);
    if (icu && srcIcu && icu.keyword === 'plural') {
      const items: { quantity: string; value: string }[] = [];
      for (const category of icu.categories) {
        const quantity = ANDROID_PLURAL_QUANTITIES.has(category.name)
          ? category.name
          : EXPLICIT_QUANTITY[category.name];
        if (!quantity) {
          warn.warnings.push(`${namespace}:${path} — plural category "${category.name}" has no Android quantity; skipped`);
          continue;
        }
        const srcBody = srcIcu.categories.find((c) => c.name === category.name)?.body ?? category.body;
        const full = `${icu.before}${category.body}${icu.after}`;
        const srcFull = `${srcIcu.before}${srcBody}${srcIcu.after}`;
        items.push({ quantity, value: escapeAndroid(positionalize(full, srcFull, true)) });
      }
      out.push({ kind: 'plurals', name, items });
      continue;
    }
    if (icu && icu.keyword !== 'plural') {
      warn.warnings.push(`${namespace}:${path} — ICU ${icu.keyword} has no Android equivalent; exported verbatim`);
      out.push({ kind: 'string', name, value: escapeAndroid(v) });
      continue;
    }

    out.push({ kind: 'string', name, value: escapeAndroid(positionalize(v, src, false)) });
  }
}

export function emitAndroidXml(
  namespaces: { namespace: string; tree: LocaleTree; sourceTree: LocaleTree }[],
): { xml: string; warnings: string[] } {
  const warn: AndroidWarnings = { warnings: [] };
  const entries: Entry[] = [];
  for (const { namespace, tree, sourceTree } of namespaces) {
    walk(tree, sourceTree, namespace, '', entries, warn);
  }

  const lines: string[] = ['<?xml version="1.0" encoding="utf-8"?>', '<!-- generated by i18n-agent — do not edit -->', '<resources>'];
  for (const e of entries) {
    if (e.kind === 'string') {
      lines.push(`    <string name="${e.name}">${e.value}</string>`);
    } else if (e.kind === 'plurals') {
      lines.push(`    <plurals name="${e.name}">`);
      for (const item of e.items ?? []) {
        lines.push(`        <item quantity="${item.quantity}">${item.value}</item>`);
      }
      lines.push('    </plurals>');
    } else {
      lines.push(`    <string-array name="${e.name}">`);
      for (const item of e.arrayItems ?? []) {
        lines.push(`        <item>${escapeAndroid(item)}</item>`);
      }
      lines.push('    </string-array>');
    }
  }
  lines.push('</resources>', '');
  return { xml: lines.join('\n'), warnings: warn.warnings };
}

export function writeAndroidResources(
  outDir: string,
  lang: string,
  isSource: boolean,
  xml: string,
): string {
  const dir = join(outDir, isSource ? 'values' : `values-${lang}`);
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'strings.xml');
  writeFileSync(path, xml, 'utf8');
  return path;
}
