import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { flattenTree, type LocaleTree } from '../locale-files.js';
import { keyId } from '../lockfile.js';

// web-json: re-emit the canonical layout as JSON per language (canonical YAML
// becomes JSON for web consumers; layout — flat file or namespace dirs — is
// mirrored).
export function writeWebJson(
  outDir: string,
  lang: string,
  layoutKind: 'flat' | 'namespaces',
  trees: { namespace: string; tree: LocaleTree }[],
): string[] {
  const written: string[] = [];
  for (const { namespace, tree } of trees) {
    const path =
      layoutKind === 'flat' ? join(outDir, `${lang}.json`) : join(outDir, lang, `${namespace}.json`);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, `${JSON.stringify(tree, null, 2)}\n`, 'utf8');
    written.push(path);
  }
  return written;
}

// ts-keys: generated union types for typo-proof t() calls.
export function emitTsKeys(namespaces: { namespace: string; tree: LocaleTree }[]): string {
  const nsNames: string[] = [];
  const keys: string[] = [];
  for (const { namespace, tree } of namespaces) {
    if (namespace) nsNames.push(namespace);
    for (const [key, value] of flattenTree(tree)) {
      if (typeof value === 'string') {
        keys.push(namespace ? keyId(namespace, key) : key);
      }
    }
  }
  const union = (items: string[]) =>
    items.length > 0 ? items.map((i) => `  | '${i.replace(/'/g, "\\'")}'`).join('\n') : '  | never';
  return `// generated by i18n-agent — do not edit
export type I18nNamespace =
${union(nsNames)};

export type I18nKey =
${union(keys)};
`;
}

export function writeTsKeys(outDir: string, content: string): string {
  const path = outDir.endsWith('.ts') ? outDir : join(outDir, 'i18n-keys.d.ts');
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
  return path;
}
