// generated by i18n-agent — do not edit
export type I18nNamespace =
  | 'auth'
  | 'common';

export type I18nKey =
  | 'auth:login.title'
  | 'auth:login.button'
  | 'auth:login.forgot'
  | 'auth:errors.invalid'
  | 'common:appName'
  | 'common:greeting'
  | 'common:search.placeholder'
  | 'common:search.empty'
  | 'common:files'
  | 'common:footer'
  | 'common:saveButton';
